version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: